### ISSUE TITLE
PSNR-HVS-M function fails on this image comparison.

### ISSUE THREAD

**Issue by LostVector** [Rolinh/VQMT#1]
PSNR_HVS_M calculation fails with these two images (after decoding the jpg to bmp, padding if necessary) and comparing the two.

The error bubbles up from the compute / maskeff function in PSNRHVS.cpp, where the line "float pop = vari(z)" returns 0.  Then the subsequent calculation divides by pop, which of course is NaN, then it is all downhill from there.

![reference](https://cloud.githubusercontent.com/assets/7145755/6649755/33a7f43e-c9b0-11e4-8b69-a203ffbc1888.png)

![test_jpg_0](https://cloud.githubusercontent.com/assets/7145755/6649757/3d64f56c-c9b0-11e4-84a5-95cf27a2ec53.jpg)

**Comment by rolinh** [comment]
Hi. I will look into that, thanks for reporting.

**Comment by LostVector** [comment]
Upon further inspection and seeing the original matlab code for PSNR-HVS-M, the line

if( pop != FLT_EPSILON ) {

should probably be 

if (fabsf(pop) > FLT_EPSILON) {

**Comment by rolinh** [comment]
That seems right actually. Checking `pop != FLT_EPSILON` does not make sense. I will push that change. Tell me if that fixes your issue.

**Comment by rolinh** [comment]
@LostVector can you confirm the fix?

**Comment by LostVector** [comment]
Looks good.  Thanks.
