### ISSUE TITLE
How do I use this similar function using Python

### ISSUE THREAD

**Issue by djangid** [Rolinh/VQMT#5]
Need support using Python if possible

**Comment by rolinh** [comment]
What function are you talking about? VQMT is not a library, it is a standalone program to compute image quality metrics.

**Comment by djangid** [comment]
any help how can i convert this to python program, also what all things it does. i have some internal project which i would like to do for myself to learn vedio quality where i need to check the quality of video

**Comment by rolinh** [comment]
What it does is documented: it computes different image quality metrics.
If you want to learn how this is done, read the source code, it definitely is not a lot.

If you want to see a stupid/simple python implementation of SSIM for instance, you can have a look at [pyuvssim](https://github.com/Rolinh/pyuvssim/), something I wrote long ago.

Now if you want to re-implement VQMT in python, there is no secret sauce: understand what it does and replicate.

**Comment by djangid** [comment]
thanks a lot i dont know c++ thats why i was asking the questions anyways i will go through the code

**Comment by rolinh** [comment]
This code is quite straight forward so you should be able to get a grasp even without C++ knowledge.
